# Write your query or mutation here
query Factions {
  factions {
    id
    name
    capital
    money
    win
    loose
    color
    img {
      url
    }
    chef
    frontColor
    players {
      id
    }
    regions {
      id
    }
  }
}