# Write your query or mutation here
query Factions($id: ID!) {
  faction(id: $id) {
    frontColor
    players {
      id
      name
      img {
        url
      }
      region {
        name
        null {
          id
          name
          adjacents {
            id
            name
          }
          null {
            id
            name
          }
        }
        adjacents {
          id
          name
          adjacents {
            id
            name
          }
          null {
            id
            name
          }
        }
      }
    }
  }
}