# Write your query or mutation here
query Region($id: ID!) {
  region(id: $id) {    
    id
    name
  	description
    map
    img
    game
    minimap {
      url
    }
    matches {
      match
    }
    color
    mapdl
    fight
    players {
      prisonnier
      name
      win
      lose
      handicap
      faction {
        frontColor
      }
      img {
        url
      }
    }
  }
}