query Matchs {
  matchs {
    id
    match
    replay
    youtube
    actif
    win
    lose
    region {
      name
      img
      map
      description
      players {
        name
        faction {
          name
        }
      }
      faction {
        color
        name
      }
    }
  }
}