mutation($id: InputID, $match: String!, $actif: Boolean!, $region: ID){
  updateMatch(input: {
    where: $id,
    data: {
      match: $match,
      actif: $actif,
      region: $region
    }
  }){
    match{
      id
      match
    }
  }
}

#{
#  "id": {"id" : "60abeb9ba8304222842992fa"},
#  "match": "NOUVEAU MATCH UPDATE",
#  "actif": true,
#  "region": "60a23b4d29325b1bc0566dad"
#}